sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dadsweb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dadsweb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'Doc-react'
  env: 'Docreact-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-322332634763'
  bucket_path: 'Doc-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
